apiVersion: v1
kind: Service
metadata:
  name: config
  labels:
    svc: config
    ver: v1
  namespace: sb
spec:
  #type: NodePort
  ports:
    - port: 9091
      targetPort: 39091
      protocol: TCP
      name: http
  selector:
    app: config
    ver: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  namespace: sb
spec:
  selector:
    matchLabels:
      app: config
      ver: v1
  replicas: 1
  template:
    metadata:
      name: config
      labels:
        app: config
        ver: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "PORT_HTTP"
        prometheus.io/path: "/prometheus"
    spec:
      containers:
        - name: config
          imagePullPolicy: IfNotPresent
          image: vgpu/config:latest
          #command: ['sleep','10000']
          resources:
            requests:
              cpu: "2"
              memory: 2Gi
            limits:
              cpu: "2"
              memory: 2Gi
          ports:
            - containerPort: 9091
              name: http
          env:
            - name: SINGLE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace


